api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'product/$',views.ProductListView.as_view(),name='product_list'),
    url(r'product/(?P<pk>\d+)/$',views.ProductDetailView.as_view(),name='detail'),
]

coupons/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^apply/$',views.coupons_apply,name='apply'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from api import views

# router = routers.DefaultRouter()
# router.register(r'users',views.UserSerializer)
# router.register(r'groups',views.GroupSerializer)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shopping_cart/',include('shoppingcart.urls',namespace='shopping_cart')),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^coupons/',include('coupons.urls',namespace='coupons')),
    url(r'^',include('shop.urls',namespace='shop')),
    url(r'api/',include('api.urls',namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',views.order_create,name='order_create'),
    url(r'^order_detail/$',views.order_detail,name='order_detail'),
    url(r'^remove/(?P<order_id>\d+)/$',views.order_delete,name='order_delete'),
]

shoppingcart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.shopping_cart_detail,
        name='shopping_cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.shopping_cart_add,
        name='shopping_cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.shopping_cart_remove,
        name='shopping_cart_remove'),
]

shoppingcart/models.py
from django.db import models

# Create your models here.

shoppingcart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class ShoppingCartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int) # 转换成int
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shoppingcart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .shoppingcart import ShoppingCart
from .forms import ShoppingCartAddProductForm
from coupons.models import Coupons
from coupons.forms import CouponsForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
# Create your views here.

# 只响应POST状态的请求
# @require_POST
# @login_required
def shopping_cart_add(request,product_id):
    # 初始化购物车的信息,生成购物车会话ID
    shopping_cart = ShoppingCart(request)
    product = get_object_or_404(Product,id=product_id)
    form = ShoppingCartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        shopping_cart.add(product=product,
                          # user=username,
                          quantity=cd['quantity'],
                          update_quantity=cd['update'])
    # 重定向到该视图
    return redirect('shopping_cart:shopping_cart_detail')

def shopping_cart_remove(request,product_id):
    shopping_cart = ShoppingCart(request)
    product = get_object_or_404(Product,id=product_id)
    shopping_cart.remove(product)
    return redirect('shopping_cart:shopping_cart_detail')


# 购物车详情
def shopping_cart_detail(request):
    shopping_cart = ShoppingCart(request)
    for item in shopping_cart:
        item['update_quantity_form'] = ShoppingCartAddProductForm(initial={'quantity':item['quantity'],'update':True})
    # 引入优惠券表单
    coupon_apply_form = CouponsForm()
    return render(request,
                  'shopping_cart/detail.html',
                  {'shopping_cart':shopping_cart,
                   'coupon_apply_form':coupon_apply_form})

shoppingcart/templates/shopping_cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ request.user.last_name }}的购物车
{% endblock %}

{% block content %}
    <h1>{{ request.user.last_name }}的购物车</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>图片</th>
                <th>商品</th>
                <th>数量</th>
                <th>删除</th>
                <th>单价</th>
                <th>价格</th>
            </tr>
        </thead>
        <tbody>
        {% for item in shopping_cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
{#                    <td>{{ item.quantity }}</td>#}
                    <td>
                        <form action="{% url "shopping_cart:shopping_cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="修改">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url "shopping_cart:shopping_cart_remove" product.id %}">删除</a></td>
                    <td class="num">￥:{{ item.price }}元</td>
                    <td class="num">￥:{{ item.total_price }}元</td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if shopping_cart.coupon %}
        <tr class="subtotal">
            <td>小计</td>
            <td colspan="4"></td>
            <td class="num">¥{{ shopping_cart.get_total_price }}</td>
        </tr>
        <tr>
            <td>
                "{{ shopping_cart.coupon.code }}" 优惠
                (- {{ shopping_cart.coupon.discount }} %)
            </td>
            <td colspan="4"></td>
            <td class="num neg">
                - ¥{{ shopping_cart.get_discount|floatformat:"2" }}
            </td>
        </tr>
        {% endif %}
        <tr class="total">
            <td>合计人民币</td>
            <td colspan="4"></td>
            <td class="num">{{ shopping_cart.get_total_price_after_discount|floatformat:"2" }}元</td>
        </tr>
        </tbody>
    </table>
    <p>在此输入优惠券代码:</p>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="确认">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button">继续购物</a>
        <a href="{% url "orders:order_create" %}" class="button">结账</a>
    </p>
{% endblock %}