api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'product/$',views.ProductListView.as_view(),name='product_list'),
    url(r'product/(?P<pk>\d+)/$',views.ProductDetailView.as_view(),name='detail'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from api import views

# router = routers.DefaultRouter()
# router.register(r'users',views.UserSerializer)
# router.register(r'groups',views.GroupSerializer)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shopping_cart/',include('shoppingcart.urls',namespace='shopping_cart')),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^coupons/',include('coupons.urls',namespace='coupons')),
    url(r'^',include('shop.urls',namespace='shop')),
    url(r'api/',include('api.urls',namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',views.order_create,name='order_create'),
    url(r'^order_detail/$',views.order_detail,name='order_detail'),
    url(r'^remove/(?P<order_id>\d+)/$',views.order_delete,name='order_delete'),
]

orders/models.py
from django.db import models
from shop.models import Product
from decimal import Decimal
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator
from coupons.models import Coupons
from decimal import Decimal
# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(User,related_name='user_order',db_index=True,verbose_name='用户')
    first_name = models.CharField(max_length=50,verbose_name='姓氏')
    last_name = models.CharField(max_length=50,verbose_name='名')
    email = models.EmailField(verbose_name='邮箱')
    address = models.CharField(max_length=200,verbose_name='收货地址')
    postal_code = models.CharField(max_length=20,verbose_name='邮政编码')
    city = models.CharField(max_length=100,verbose_name='所在城市')
    created = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='最后修改时间')
    paid = models.BooleanField(default=False,verbose_name='订单状态')   # 判断已完成和未完成订单
    coupon = models.ForeignKey(Coupons,related_name='orders',null=True,blank=True)
    discount = models.IntegerField(default=0,validators=[MaxValueValidator(100),MinValueValidator(0)])
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    # 得到所有商品的总消费
    def get_total_cost(self):
        total_cost =  sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount  / Decimal('100'))

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items')
    product = models.ForeignKey(Product,related_name='order_items')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)
    # 得到某件商品的总消费
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email','address','postal_code','city','paid']

orders/views.py
from django.shortcuts import render,redirect
from .models import OrderItem,Order
from .forms import OrderCreateForm
from .tasks import order_created
from shoppingcart.shoppingcart import ShoppingCart
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def order_create(request):
    order_items = Order.objects.filter(user_id=request.user.id)
    items =[ order for order in order_items]
    shopping_cart = ShoppingCart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_order = form.save(commit=False)
            new_order.paid = True
            new_order.user = request.user
            new_order = form.save(commit=False)
            if shopping_cart.coupon:
                new_order.coupon = shopping_cart.coupon
                new_order.discount = shopping_cart.coupon.discount
            new_order.save()
            # 为购物车每件商品创建数据库实例信息
            for item in shopping_cart:
                OrderItem.objects.create(order=new_order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # 清空购物车
            shopping_cart.clear()
            # 调用异步任务
            # order_created.delay(new_order.id)
            return render(request,'orders/order/created.html',{'order':new_order})
    else:
        form = OrderCreateForm(initial={'first_name':items[0].first_name,'last_name':items[0].last_name,'email':items[0].email})
    return render(request,
                  'orders/order/create.html',
                  {'shopping_cart':shopping_cart,
                   'form':form})


def order_detail(request):
    order_detail = OrderItem.objects.all()
    order = Order.objects.filter(paid=True,user=request.user.id)
    if order:
        order_detail = order_detail.filter(order=order)
    return render(request,
                  'orders/order/order_detail.html',
                  {'order_detail':order_detail})


def order_delete(request,order_id):
    # order = OrderItem.objects.filter(id=order_id)
    Order.objects.get(id=order_id).delete()
    return redirect('orders:order_detail')

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
    结算
{% endblock %}

{% block content %}
    <h1>结算</h1>
    <div class="order-info">
        <h3>你的订单详情</h3>
        <ul>
            {% for item in shopping_cart %}
                <li>
                    {{ item.quantity }} x {{ item.product.name }}
                    <span>￥:{{ item.total_price }}</span>
                </li>
            {% endfor %}
            {% if shopping_cart.coupon %}
               <li>"{{ shopping_cart.coupon.code }}"
                   ( - {{ shopping_cart.coupon.discount }} %)
                    <span> - ¥{{ shopping_cart.get_discount|floatformat:"2" }}</span>
                </li>
            {% endif %}
        </ul>
        <p>总共￥:{{ shopping_cart.get_total_price_after_discount }}元</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="请确认订单"></p>
        {% csrf_token %}
    </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>Thank you</h1>
    <p>您的订单已经付款成功,订单号是:<strong>{{ order.id }}</strong></p>
{% endblock %}

orders/templates/orders/order/order_detail.html
{% extends "shop/base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>历史订单</h1>
{#    <div id="main" class="product-list">#}
{#    <p>您的订单历史订单有:</p>#}
{#    {% for order in order_detail %}#}
{#        <p>订单编号:{{ order.order.id }}</p>#}
{#    <p>商品名称:{{ order.product.name }}</p>#}
{##}
{#    <a href="{{ order.product.get_absolute_url }}">#}
{#        <img src="{{ order.product.image.url }}" style="width: 350px; height: 360px;">#}
{#    </a>#}
{#    <p>价格:{{ order.price }}</p>#}
{#    <p>数量:{{ order.quantity }}</p>#}
{#    <p>收件人信息:{{ order.order.first_name }}</p>#}
{#    {% endfor %}#}
{#    </div>#}
    <div class="row">
  {% for order in order_detail %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <p>订单编号:{{ order.order.id }}</p>
      <a href="{{ order.product.get_absolute_url }}">
        <img src="{{ order.product.image.url }}" alt="..." style="width: 150px; height: 150px">
      </a>
      <div class="caption">
        <h4>{{ order.product.name }}</h4>
        <p>...</p>
        <p><a href="{% url "orders:order_delete" order.order.id %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-remove-sign"></span></a></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}