account/urls.py
from  django.conf.urls import url
from . import  views
# from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$','django.contrib.auth.views.login',name='login'),
    # url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',name='logout1'),
    # url(r'^logout/$',views.logout,name='logout1'),
    url(r'^logout-then-login/$','django.contrib.auth.views.logout_then_login',name='logout_then_login'),
]

api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'product/$',views.ProductListView.as_view(),name='product_list'),
    url(r'product/(?P<pk>\d+)/$',views.ProductDetailView.as_view(),name='detail'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from api import views

# router = routers.DefaultRouter()
# router.register(r'users',views.UserSerializer)
# router.register(r'groups',views.GroupSerializer)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shopping_cart/',include('shoppingcart.urls',namespace='shopping_cart')),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^coupons/',include('coupons.urls',namespace='coupons')),
    url(r'^',include('shop.urls',namespace='shop')),
    url(r'api/',include('api.urls',namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',views.order_create,name='order_create'),
    url(r'^order_detail/$',views.order_detail,name='order_detail'),
    url(r'^remove/(?P<order_id>\d+)/$',views.order_delete,name='order_delete'),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # 检索全部商品和全部商品类型
    url(r'^search/$',
        views.get_product,
        name='search'),
    url(r'^$',views.product_list,
        name='product_list'),
    # 根据商品类别检索
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    # 查询某个商品
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shoppingcart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.shopping_cart_detail,
        name='shopping_cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.shopping_cart_add,
        name='shopping_cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.shopping_cart_remove,
        name='shopping_cart_remove'),
]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

# 商品类别
class Category(models.Model):
    name = models.CharField(max_length=200,
                            verbose_name='类别名称')  # db_index 索引
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)        # 唯一

    class Meta:
        ordering = ('name',)
        # 给Category模型取名为'category'
        verbose_name = 'category'
        # 指定模型的复数形式,如果不指定会自动在模型名称后面加一个's'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    # 构建商品类别的url
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

# 商品详情
class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products')
    name = models.CharField(max_length=200,db_index=True)                   # 商品名称
    slug = models.SlugField(max_length=200,db_index=True)                   # 商品标签
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)     # 商品图片
    description = models.TextField(blank=True)                              # 商品描述
    price = models.DecimalField(max_digits=10,decimal_places=2)             # 商品价格(十进制,max_digits设定最大值,decimal_places设定最小值)
    stock = models.PositiveIntegerField()                                   # 正整数字段,存储库存
    available = models.BooleanField(default=True)                           # 是否可购买
    created = models.DateTimeField(auto_now_add=True)                       # 创建时间
    updated = models.DateTimeField(auto_now=True)                           # 最后更新时间

    class Meta:
        ordering = ('name',)
        # 指定id,slug使用共同索引,可使用这两个字段来查询商品
        index_together = (('id','slug'),)


    def __str__(self):
        return self.name

    # 构建单一商品的url
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id,self.slug])

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(label='搜索',max_length=50)

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from shoppingcart.forms import ShoppingCartAddProductForm
from orders.models import Order,OrderItem
from .recommender import Recommender
from .forms import SearchForm
from django.db.models import Q
# Create your views here.

# 检索所有商品
def product_list(request,category_slug=None):
    category = None
    # 所有商品类别
    categories = Category.objects.all()
    # 所有有效商品
    products = Product.objects.filter(available=True)
    # 如果商品类别标签不为空
    if category_slug:
        # 根据标签查找该商品类别
        category = get_object_or_404(Category,slug=category_slug)
        # 有效商品根据标签类别进行过滤,查出该类别所有有效商品
        products = products.filter(category=category)
    return render(request,'shop/product/list.html',
                  {'category':category,
                   'categories':categories,
                   'products':products})

# 检索某个商品
def product_detail(request,id,slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    shopping_cart_product_form = ShoppingCartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product],4)
    return render(request,
                  'shop/product/detail.html',
                  {'product':product,
                   'shopping_cart_product_form':shopping_cart_product_form,
                   'recommended_products':recommended_products})



def get_product(request):
    search = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            search = Product.objects.filter(Q(name__icontains=search)|Q(slug__icontains=search))
            # print(search)
    else:
        form = SearchForm()
    return render(request,
                  'shop/product/search_list.html',
                  {'form':form,'search':search})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}购物比价商城{% endblock %}</title>
    <link href="{% static "css/base1.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">购物比价商城</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
        <li><a href="#">精选</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">其他<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">海淘</a></li>
            <li><a href="#">国内</a></li>
            <li><a href="#">好价·发现</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">闲置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">买家秀</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" action="/search/" method="POST">
        <div class="form-group">
{#            <input id="search" type="text" name="search" class="form-control" placeholder="搜点什么吧">#}
        <input id="search" type="text" name="search" class="form-control" placeholder="搜点什么吧" maxlength="200">
{#            {{ form.as_p }}#}
        </div>
        {% csrf_token %}
        <input type="submit" class="btn btn-default" value="搜索">
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li></li>
        <li><a href="#">关于本站</a></li>
        <li class="dropdown">
          {% if request.user.is_authenticated %}
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">我的关注</a></li>
            <li><a href="#">我的资料</a></li>
            <li><a href="{% url "orders:order_detail" %}">我的订单</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url "account:logout1" %}">退出</a></li>
          </ul>
          {% else %}
            <li><a href="{% url "account:login" %}">请登录</a></li>
          {% endif %}
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{#    <div id="header">#}
{#        <a href="/" class="logo">什么值得买</a>#}
{##}
{#    </div>#}
    <div id="subheader">
{#     {% if request.user.is_authenticated %}#}
{#            <ul>#}
{#                <li {% if section == "index" %}class="selected"{% endif %}>#}
{#                  <a href="{% url "shop:product_list" %}">首页</a>#}
{#                </li>#}
{#                <li {% if section == "people" %}class="selected"{% endif %}>#}
{#                    <a href="#">圈子</a>#}
{#                </li>#}
{#            </ul>#}
{#            {% endif %}#}
{#            <span class="user">#}
{#                {% if request.user.is_authenticated %}#}
{#                    Hello {{ request.user.first_name }}#}
{#                    <a href="{% url "account:logout1" %}">退出</a>#}
{#                {% else %}#}
{#                    <a href="{% url "account:login" %}">登录</a>#}
{#                {% endif %}#}
{#            </span>#}
{#            <span class="order">#}
{#                <a href="{% url "orders:order_detail" %}">我的订单</a>#}
{#            </span>#}
        <div class="cart">
{#            {% with total_items=shopping_cart|length %}#}
                {% if shopping_cart|length > 0 %}
{#                    你的购物车有:#}
                    <a href="{% url "shopping_cart:shopping_cart_detail" %}">
{#                        {{ shopping_cart|length }} 件商品{{ total_items|pluralize:"" }},#}
{#                        合计￥:{{ shopping_cart.get_total_price }}元#}
                    <button class="btn btn-primary" type="button">
                       <span class="glyphicon glyphicon-shopping-cart"></span> <span class="badge">{{ shopping_cart|length }}</span>
                     </button>
                    </a>
                {% else %}
                    你的购物车是空的!
                {% endif %}
{#                <a href="#">Inbox <span class="badge">42</span></a>#}
{##}
{#                <button class="btn btn-primary" type="button">#}
{#                  Messages <span class="badge">4</span>#}
{#                </button>#}
{#            {% endwith %}#}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>